using System.Numerics;
using System.Runtime.InteropServices;
using Hexa.NET.OpenGL;

namespace ETS2LA.Overlay.Shaders;

// WARNING: This code was AI generated by gemini. It might have unintended
//          functionality, bugs, or performance issues. Use with caution!
public class LineWithGradient : IDisposable
{
    [StructLayout(LayoutKind.Sequential, Pack = 1)]
    public struct LineVertex
    {
        public Vector2 ScreenPos; // NDC (-1 to 1)
        public Vector2 UV;        // x: -1 (outer core) to 1 (inner glow), y: 0 to 1 (progress along line)
        public Vector4 Color;     // RGBA
        public float Feather;     // Unused by HUD shader, retained for struct alignment
    }

    private readonly GL gl;
    public uint ProgramID { get; private set; }
    
    private uint vao;
    private uint vbo;
    private uint ebo;

    private readonly List<LineVertex> vertices = new();
    private readonly List<uint> indices = new();

    public LineWithGradient(GL openGL)
    {
        gl = openGL;
        ProgramID = CompileProgram(VertexShaderSource, FragmentShaderSource);
        InitGLBuffers();
    }

    private unsafe void InitGLBuffers()
    {
        vao = gl.GenVertexArray();
        vbo = gl.GenBuffer();
        ebo = gl.GenBuffer();

        gl.BindVertexArray(vao);

        gl.BindBuffer(GLBufferTargetARB.ArrayBuffer, vbo);
        gl.BindBuffer(GLBufferTargetARB.ElementArrayBuffer, ebo);

        int stride = sizeof(LineVertex);

        // Location 0: ScreenPos (vec2)
        gl.EnableVertexAttribArray(0);
        gl.VertexAttribPointer(0, 2, GLVertexAttribPointerType.Float, false, stride, (void*)0);

        // Location 1: UV (vec2)
        gl.EnableVertexAttribArray(1);
        gl.VertexAttribPointer(1, 2, GLVertexAttribPointerType.Float, false, stride, (void*)(2 * sizeof(float)));

        // Location 2: Color (vec4)
        gl.EnableVertexAttribArray(2);
        gl.VertexAttribPointer(2, 4, GLVertexAttribPointerType.Float, false, stride, (void*)(4 * sizeof(float)));

        // Location 3: Feather (float)
        gl.EnableVertexAttribArray(3);
        gl.VertexAttribPointer(3, 1, GLVertexAttribPointerType.Float, false, stride, (void*)(8 * sizeof(float)));

        gl.BindVertexArray(0);
        gl.BindBuffer(GLBufferTargetARB.ArrayBuffer, 0);
        gl.BindBuffer(GLBufferTargetARB.ElementArrayBuffer, 0);
    }

    /// <summary>
    /// Adds a quad segment.
    /// UV.x = -1.0 for the Sharp Outer Edge, +1.0 for the Soft Inward Glow Edge.
    /// progressStart/progressEnd range from 0.0 (near) to 1.0 (far) for distance fading.
    /// </summary>
    public void AddGlowQuad(Vector2 outerStart, Vector2 innerStart, Vector2 innerEnd, Vector2 outerEnd, Vector4 color, float progressStart, float progressEnd, float transparentValue = 0.0f)
    {
        uint baseIndex = (uint)vertices.Count;

        vertices.Add(new LineVertex { ScreenPos = outerStart, UV = new Vector2(-1.0f, progressStart), Color = color, Feather = transparentValue });
        vertices.Add(new LineVertex { ScreenPos = innerStart, UV = new Vector2( 1.0f, progressStart), Color = color, Feather = transparentValue });
        vertices.Add(new LineVertex { ScreenPos = innerEnd,   UV = new Vector2( 1.0f, progressEnd),   Color = color, Feather = transparentValue });
        vertices.Add(new LineVertex { ScreenPos = outerEnd,   UV = new Vector2(-1.0f, progressEnd),   Color = color, Feather = transparentValue });

        indices.Add(baseIndex + 0);
        indices.Add(baseIndex + 1);
        indices.Add(baseIndex + 2);
        indices.Add(baseIndex + 0);
        indices.Add(baseIndex + 2);
        indices.Add(baseIndex + 3);
    }

    public unsafe void RenderPass()
    {
        if (vertices.Count == 0 || indices.Count == 0)
            return;

        Span<LineVertex> vtxSpan = CollectionsMarshal.AsSpan(vertices);
        Span<uint> idxSpan = CollectionsMarshal.AsSpan(indices);

        gl.BindBuffer(GLBufferTargetARB.ArrayBuffer, vbo);
        fixed (LineVertex* pVtx = vtxSpan)
        {
            gl.BufferData(GLBufferTargetARB.ArrayBuffer, vtxSpan.Length * sizeof(LineVertex), pVtx, GLBufferUsageARB.StreamDraw);
        }

        gl.BindBuffer(GLBufferTargetARB.ElementArrayBuffer, ebo);
        fixed (uint* pIdx = idxSpan)
        {
            gl.BufferData(GLBufferTargetARB.ElementArrayBuffer, idxSpan.Length * sizeof(uint), pIdx, GLBufferUsageARB.StreamDraw);
        }

        gl.Disable(GLEnableCap.DepthTest);
        gl.Enable(GLEnableCap.Blend);
        gl.BlendFunc(GLBlendingFactor.SrcAlpha, GLBlendingFactor.OneMinusSrcAlpha);

        gl.UseProgram(ProgramID);
        gl.BindVertexArray(vao);

        gl.DrawElements(GLPrimitiveType.Triangles, indices.Count, GLDrawElementsType.UnsignedInt, (void*)0);

        gl.BindVertexArray(0);
        gl.UseProgram(0);

        vertices.Clear();
        indices.Clear();
    }

    private const string VertexShaderSource = @"
#version 150
in vec2 aPos;
in vec2 aUV;
in vec4 aColor;
in float aFeather;

noperspective out vec2 FragUV;
out vec4 FragColor;

void main()
{
    FragUV = aUV;
    FragColor = aColor;
    gl_Position = vec4(aPos, 0.0, 1.0);
}";

    private const string FragmentShaderSource = @"
#version 150
noperspective in vec2 FragUV;
in vec4 FragColor;

out vec4 FinalColor;

void main()
{
    float u = FragUV.x; // -1.0 (Outer Core) to +1.0 (Inner Edge)

    // 1. Crisp outer core line
    float coreLine = 1.0 - smoothstep(-1.0, -0.75, u);

    // 2. Soft asymmetric inward light bleed
    float glowDist = clamp((u + 0.75) / 1.75, 0.0, 1.0);
    float innerGlow = pow(1.0 - glowDist, 2.2) * 0.65;

    float totalAlpha = clamp(coreLine + innerGlow, 0.0, 1.0);

    // 3. Smooth fadeout near the horizon (FragUV.y = distance progress)
    float distanceFade = 1.0 - smoothstep(0.7, 1.0, FragUV.y);

    // Pop the brightness on the crisp outer edge
    vec3 finalRGB = FragColor.rgb + vec3(0.35) * coreLine;

    FinalColor = vec4(finalRGB, FragColor.a * totalAlpha * distanceFade);
}";

    private uint CompileProgram(string vertSrc, string fragSrc)
    {
        uint vert = gl.CreateShader(GLShaderType.VertexShader);
        gl.ShaderSource(vert, vertSrc);
        gl.CompileShader(vert);

        uint frag = gl.CreateShader(GLShaderType.FragmentShader);
        gl.ShaderSource(frag, fragSrc);
        gl.CompileShader(frag);

        uint prog = gl.CreateProgram();
        gl.AttachShader(prog, vert);
        gl.AttachShader(prog, frag);
        gl.LinkProgram(prog);

        gl.DeleteShader(vert);
        gl.DeleteShader(frag);
        return prog;
    }

    public void Dispose()
    {
        if (vbo != 0) gl.DeleteBuffer(vbo);
        if (ebo != 0) gl.DeleteBuffer(ebo);
        if (vao != 0) gl.DeleteVertexArray(vao);
        if (ProgramID != 0) gl.DeleteProgram(ProgramID);
    }
}